---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(conflicted)
library(dplyr)
library(readr)
library(EnhancedVolcano)
library(ggrepel)
conflict_prefer("filter", "dplyr")
```

### SR vs LR - T0
```{r}
resIHW = read_tsv("../../data/70_de_analysis/72_run_de/deseq2_res_bulk_response_t0/short_term_long_term_IHWallGenes.tsv")
```

```{r, fig.width=12, fig.height=10}
fdr_cutoff = 0.1
fc_cutoff = 1
EnhancedVolcano(resIHW,
                lab = resIHW$gene_id,
                x = "log2FoldChange",
                y = "padj",
                pCutoff = fdr_cutoff,
                FCcutoff = fc_cutoff,
                boxedLabels=TRUE,
                drawConnectors = TRUE,
                subtitle = "",
                legendPosition = "right",
                maxoverlapsConnectors = Inf,
                caption = paste0("fold change cutoff: ", round(2**fc_cutoff, 1), ", adj.p-value cutoff: ", fdr_cutoff),
                title = "short term vs. long term (T0)",
                selectLab = c("LGR5", "MYO7B",  "CD24", "MOXD1",  "RHOB",  "KLF2",  "ITGB1",  "OSTN",  "TUSC1",  "XIST", "GABRA3"))
```


### Post vs Pre SR-2/3

```{r}
resIHW = read_tsv("../../data/70_de_analysis/72_run_de/deseq2_res_bulk_timepoints/post-treatment_pre-treatment_IHWallGenes.tsv")
```

```{r, fig.width=12, fig.height=10}
fdr_cutoff = 0.1
fc_cutoff = 1
EnhancedVolcano(resIHW,
                lab = resIHW$gene_id,
                x = "log2FoldChange",
                y = "padj",
                pCutoff = fdr_cutoff,
                FCcutoff = fc_cutoff,
                boxedLabels=TRUE,
                drawConnectors = TRUE,
                subtitle = "",
                legendPosition = "right",
                maxoverlapsConnectors = Inf,
                caption = paste0("fold change cutoff: ", round(2**fc_cutoff, 1), ", adj.p-value cutoff: ", fdr_cutoff),
                title = "Post. vs. Pre SR2 and SR3",
                selectLab = c("FAM177B", "CCR1", "MYO7B", "DUSP5", "PALLD", "ALOX5", "KLF10", "CDKN2C"))
```



### FOS malignant vs other malignant

```{r}
resIHW = read_tsv("../../data/70_de_analysis/72_run_de/deseq2_res_sc_fosb_b_cells/fos_malignant_b_malignant_b_IHWallGenes.tsv")
```

```{r, fig.width=12, fig.height=10}
fdr_cutoff = 0.1
fc_cutoff = 1
EnhancedVolcano(resIHW,
                lab = resIHW$gene_id,
                x = "log2FoldChange",
                y = "padj",
                pCutoff = fdr_cutoff,
                FCcutoff = fc_cutoff,
                boxedLabels=TRUE,
                drawConnectors = TRUE,
                subtitle = "",
                legendPosition = "right",
                maxoverlapsConnectors = Inf,
                caption = paste0("fold change cutoff: ", round(2**fc_cutoff, 1), ", adj.p-value cutoff: ", fdr_cutoff),
                title = "Fos+ malignant B cells vs other malignant B cells",
                selectLab = c("FOS", "KLF4", "JUND", "DUSP1", "RGS1", "KLF6", "TNF", "DUSP6", "XIST", "RHOB", "GPR183", "KLF2"))
```

### malignant B vs. B 

```{r}
resIHW = read_tsv("../../data/70_de_analysis/72_run_de/deseq2_res_sc_healthy_vs_malignant_b_cells/malignant_healthy_IHWallGenes.tsv")
```

```{r, fig.width=12, fig.height=10}
fdr_cutoff = 0.1
fc_cutoff = 1
EnhancedVolcano(resIHW,
                lab = resIHW$gene_id,
                x = "log2FoldChange",
                y = "padj",
                pCutoff = fdr_cutoff,
                FCcutoff = fc_cutoff,
                boxedLabels=TRUE,
                drawConnectors = TRUE,
                subtitle = "",
                legendPosition = "right",
                maxoverlapsConnectors = Inf,
                caption = paste0("fold change cutoff: ", round(2**fc_cutoff, 1), ", adj.p-value cutoff: ", fdr_cutoff),
                title = "malignant vs. healthy B cells",
                selectLab = c("ILR2", "DUSP6", "GAS7", "IL2RA", "SYT1", "STAG3", "HOPX", "KLF4", "ITGB1", "FLT3", "IL1R2", "HLA-DRB1", "HLA-DQA1", "S100A4"))
```

